[general]
import = ["~/.config/alacritty/tokyodark.toml"]

[window]
# opacity = 0.95

[font]
size = 15.5
normal.family = "firacode nerd font"
bold.family = "firacode nerd font"
italic.family = "firacode nerd font"

[colors.cursor]
background = "#dddddd"

[colors.selection]
background = "#4d4d4d"
text       = "#ffffff"

[[keyboard.bindings]]
key="K"
mods="Control|Shift"
action="ScrollLineUp"

[[keyboard.bindings]]
key="J"
mods="Control|Shift"
action="ScrollLineDown"
